name: Fetch API & Commit Data (Node)

on:
  schedule:
    # - cron: "0 * * * *"   # every hour
    # - cron: "*/5 * * * *" # every five mins
    - cron: "0 0 1 */3 *"   # every three months
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¦ Checkout
        uses: actions/checkout@v4

      - name: ğŸš§ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"

      - name: ğŸ¤– Setup Project
        run: npm ci

      - name: ğŸŒ Fetch
        env:
          MAX_RETRIES: "3"
        run: npm run prefetch

      - name: ğŸ‘· Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: ğŸ‰ Commit
        run: |
          if ! git diff --quiet; then
            git add current_seasonal.json
            git commit -m "Update data from API"
            git push
          else
            echo "No changes detected."
          fi
